language: generic

branches:
  only:
  - master

jobs:
  include:
    - stage: VMware.PSDesiredStateConfigurationTests
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
      workspaces:
        create:
          name: coverage
          paths:
            - coverage.txt
      script:
        - pwsh -File './Build/enableExperimentalFeature.ps1'
        - pwsh -File './Build/VMware.PSDesiredStateConfiguration.TestRuns.ps1'
        - PsdsCoverageResult=`cat /tmp/coverage_result.txt`
        - echo $PsdsCoverageResult > coverage.txt
    - stage: Build
      os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
      workspaces:
        use: coverage
      before_install:
        - chmod +x Build/travis-push.sh
      script:
        - PsdsCoverageResult=`cat coverage`
        - echo $PsdsCoverageResult > '/tmp/coverage_result'
        - pwsh -File './Build/build.ps1'
      after_success:
        - '[ "${TRAVIS_EVENT_TYPE}" = "push" ] && [ "${TRAVIS_BRANCH}" = "master" ] && Build/travis-push.sh'
